version: '3.3'

services:

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  nitter:
    image: epenguincom/nitter:latest
    container_name: nitter
    restart: unless-stopped
    volumes:
      - ./data/nitter:/data
    depends_on:
      - redis
    environment:
      NITTER_SERVER_NAME: "nitter.domain.tld"
      NITTER_SERVER_TITLE: "nitter""
      CACHE_REDIS_HOST: "redis"
      CACHE_REDIS_PORT: 6379
      CONFIG_HMAC_KEY: "my+strong+key"
    ports:
      - "127.0.0.1:58080:8080"
