name: Docker Image CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up build timestamp
      run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: epenguincom/nitter:latest, epenguincom/nitter:build-${{ env.timestamp }}
